#!/usr/bin/env python3
"""
This script is used to update Trust Stores for Secure Network Analytics (SNA) appliances managed by a single
SNA Manager appliance.

See comprehensive details about this script and its impacts and limitations in the corresponding README.md file.
"""

import argparse
import logging
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from time import sleep
from typing import Optional, Tuple

import requests


PATH_CM_APPLIANCES = '/cm/inventory/appliances'
PATH_CM_INVENTORY = '/cm/inventory/appliances'
PATH_CM_APPLIANCES_STATUS = '/cm/monitor/appliances/status'
PATH_CM_APPLIANCE_STATUS = '/cm/config/appliance/{}/status'
PATH_CM_CSR = '/cm/config/appliance/{}/certificate/csr'
PATH_CM_CONFIG = '/cm/config/appliance/{}/config'


class NoMatchingAppliancesError(Exception):
    """Thrown when no appliances match the specified criteria"""


class InvalidApplianceFqdnError(Exception):
    """Thrown when an appliance of a specific fqdn cannot be found"""


class InvalidApplianceIdError(Exception):
    """Thrown when an appliance of a specific id cannot be found"""


class ApplianceStatusError(Exception):
    """Thrown when Central Management actions are requested for an appliance that is not in the "up" state"""


class FailoverStateException(Exception):
    """Thrown when attempting to manage appliances via a secondary Manager appliance"""


class AuthenticationError(Exception):
    """Thrown when authentication to SNA fails"""


class InvalidFriendlyNameError(Exception):
    """Thrown when an invalid friendly name is supplied"""


class InvalidActionError(Exception):
    """Thrown when an invalid action name is requested"""


def get_command_line_args() ->  argparse.Namespace:
    """
    Gets command line args
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('-m', '--manager-address', required=True, type=str,
                        help='Address (ip/hostname) of the primary Manager appliance')
    parser.add_argument('-f', '--file', required=True, type=str, help='Path to the certificate file')
    parser.add_argument('--fqdns', required=True, nargs='+', type=str,
                        help='A space-separated list of FQDNs of appliances on which to install the new CA certificate ' \
                             'and/or to check for the presence of the CA certificate. ' \
                             'Use "all" as a shortcut to update all appliances. Note that appliance FQDNs must match ' \
                             'the appliance FQDNs shown in Central Management.')
    parser.add_argument('--friendly-name', required=False, default=_generate_friendly_name(), type=str,
                        help='Friendly name to display in Central Management for the certificate')
    parser.add_argument('-a', '--action', choices=['add', 'del', 'check'], default='add', type=str,
                        help='The action to perform on the trust stores: add a new certificate, delete an existing ' \
                             'certificate, or check certificate presence (default: add)')
    parser.add_argument('-i', '--verify-false', action='store_true', default=False,
                        help='Do not verify certificates when connecting to the SNA Manager (default: False)')
    parser.add_argument('-t', '--monitor-timeout', required=False, default=1800, type=int,
                        help='Timeout (seconds) for monitoring completion of Trust Store updates (default: 1800)')
    parser.add_argument('-d', '--debug', action='store_true', default=False, help='Enable debug logging (default: False)')
    return parser.parse_args()


def _get_credentials() ->  Tuple[str, str]:
    """
    Retrieves username/password credentials from the environment.
    IMPLEMENT ALTERNATIVE CREDENTIAL RETRIEVAL CODE HERE IF NEEDED.
    """
    username = os.getenv('USERNAME')
    password = os.getenv('PASSWORD')
    return username, password


def _is_valid_friendly_name(friendly_name: str) -> bool:
    """Indicates whether the provided name matches SNA's character restrictions"""
    pattern = r'^[a-zA-Z0-9\-_\.]+$'
    return bool(re.match(pattern, friendly_name))


def _generate_friendly_name() -> str:
    """Generates a friendly_name indicative of being auto-generated by a particular script execution"""
    return f'added_{datetime.now().strftime("%m-%d-%Y_%H.%M.%S")}'


class ApiClient:
    """
    Client of an SNA Manager
    """

    def __init__(self, manager_address: str, username: str, password: str, verify_false: bool = False):
        self.manager_address = manager_address
        self._username = username
        self._password = password
        self._cookie_jar = None
        self._xsrf_token = None
        self._verify_false = verify_false

    def authenticate(self) -> None:
        """
        Authenticate to the Manager (get stealthwatch.jwt cookie and XSRF token)
        """
        requests_kwargs = {}
        if self._verify_false:
            requests_kwargs['verify'] = False
        auth_url = f'https://{self.manager_address}/token/v2/authenticate'
        data = {'username': self._username, 'password': self._password}
        response = requests.post(auth_url, data=data, **requests_kwargs)
        if not response.status_code == 200:
            raise AuthenticationError
        self._cookie_jar = response.cookies
        self._xsrf_token = self._cookie_jar['XSRF-TOKEN']

    def refresh_token(self) -> None:
        """Refreshes the SNA JWT (expires every 20 min)"""
        requests_kwargs = {}
        if self._verify_false:
            requests_kwargs['verify'] = False
        response = requests.post(f'https://{self.manager_address}/token/v2', cookies=self._cookie_jar,
                                 headers={'X-XSRF-TOKEN': self._xsrf_token}, **requests_kwargs)
        response.raise_for_status()
        self._cookie_jar = response.cookies
        self._xsrf_token = self._cookie_jar['XSRF-TOKEN']

    def _get_cm_url(self, url: str) ->  requests.Response:
        """Performs a GET request to the specified Central Management URL."""
        requests_kwargs = {}
        if self._verify_false:
            requests_kwargs['verify'] = False
        response = requests.get(f'https://{self.manager_address}{url}', cookies=self._cookie_jar, **requests_kwargs)
        if response.status_code == 307:
            raise FailoverStateException
        response.raise_for_status()
        return response

    def _put_cm_url(self, url, **requests_kwargs) -> requests.Response:
        """Performs a PUT request to the specified Central Management URL."""
        headers={'X-XSRF-TOKEN': self._xsrf_token}
        if 'headers' in requests_kwargs:
            headers.update(requests_kwargs['headers'])
            del requests_kwargs['headers']
        if self._verify_false:
            requests_kwargs['verify'] = False
        response = requests.put(f'https://{self.manager_address}{url}', cookies=self._cookie_jar, headers=headers,
                                **requests_kwargs)
        if response.status_code == 307:
            raise FailoverStateException
        response.raise_for_status()
        return response

    def cm_inventory(self) -> dict:
        """Returns the appliance inventory from Central Management."""
        return self._get_cm_url(PATH_CM_APPLIANCES).json()

    def appliances_status(self) -> dict:
        """Returns the appliances statuses from Central Management."""
        return self._get_cm_url(PATH_CM_APPLIANCES_STATUS).json()

    def appliance_status(self, appliance_id) -> dict:
        """Returns the status details of a specific appliance from Central Management."""
        return self._get_cm_url(PATH_CM_APPLIANCE_STATUS.format(appliance_id)).json()

    def cm_config(self, appliance_id: str) -> Tuple[str, dict]:
        """
        Retrieve Central Management configuration data for the specified appliance
        """
        response = self._get_cm_url(PATH_CM_CONFIG.format(appliance_id))
        return response.headers.get('ETag', ''), response.json()

    def stage_truststore_cert(self, appliance_id: str, friendly_name: str, pemfile: str):
        filename = Path(pemfile).name
        files = {
            'friendlyName': (None, friendly_name),  # No filename is needed for this field
            'targetCertificateFile': (filename, open(pemfile, 'rb'), 'application/x-x509-ca-cert'),
        }
        return self._put_cm_url(PATH_CM_CSR.format(appliance_id), files=files)

    def update_cm_config(self, appliance_id: str, etag: str, config: dict) -> None:
        self._put_cm_url(PATH_CM_CONFIG.format(appliance_id), headers={"If-Match": etag}, json=config)



def _process_fqdns(api_client: ApiClient, appliance_fqdns: Optional[list[str]] = None) -> dict[str, str]:
    """
    Validate the provided FQDNs (or if appliance_fqdns is None, collect the list of all FQDNs from Central Management)

    FQDN validation entails ensuring that all specified FQDNs correlate to appliances present in the Central Management
    inventory and that all appliances are "up" and ready for configuration changes.
    """
    # Collect and transform cluster info
    inventory = api_client.cm_inventory()
    inventory_by_fqdn = {appl['fqdn']: appl for appl in inventory}
    appliances_statuses = api_client.appliances_status()
    status_by_fqdn = {appl['fqdn']: appl.get('configurationChannelStatus') for appl in appliances_statuses}
    appliance_fqdns = appliance_fqdns or list(inventory_by_fqdn.keys())  # if no list provided, do all appliances

    # iterate through provided FQDNs
    appliance_ids = {}
    for fqdn in appliance_fqdns:
        # perform fqdn and appliance status validations
        status = status_by_fqdn.get(fqdn)
        if not status:
            raise InvalidApplianceFqdnError(f'"{fqdn}" is not an appliance FQDN in the Central Manager inventory.')
        if not status == 'up':
            raise ApplianceStatusError(f'Appliance "{fqdn}" is not in "up" status.')
        appliance_id = inventory_by_fqdn.get(fqdn).get('id')
        if not appliance_id:
            raise ApplianceStatusError(f'Cannot find "id" attribute for appliance "{fqdn}".')
        if not api_client.appliance_status(appliance_id).get('configState') == 'UP_TO_DATE':
            raise ApplianceStatusError(f'Appliance "{fqdn}" is not ready for configuration changes.')
        appliance_ids[appliance_id] = fqdn

    return appliance_ids


def update_truststores(api_client: ApiClient, appliance_ids: list[str], friendly_name: str, cert_config: dict):
    logging.info(f'Starting Trust Store update for {len(appliance_ids)} appliances...')
    for appliance_id in appliance_ids:
        etag, cm_settings = api_client.cm_config(appliance_id)
        new_cert = {'friendlyName': friendly_name, 'certificate': cert_config}
        cm_settings['configurableElements']['trustStore']['trustedCertificates'].append(new_cert)
        api_client.update_cm_config(appliance_id, etag, cm_settings)


def delete_from_truststore(api_client: ApiClient, appliance_ids: list[str], cert_to_remove: str):
    logging.info(f'Deleting certificate from Trust Stores for {len(appliance_ids)} appliances...')
    for appliance_id in appliance_ids:
        etag, cm_settings = api_client.cm_config(appliance_id)
        current_certs = cm_settings['configurableElements']['trustStore']['trustedCertificates']
        reduced_certs = [cert for cert in current_certs if cert['certificate']['content'] != cert_to_remove]
        cm_settings['configurableElements']['trustStore']['trustedCertificates'] = reduced_certs
        api_client.update_cm_config(appliance_id, etag, cm_settings)


def check_completion(api_client: ApiClient, appliance_ids: list[str], cert: str, presence: bool = True) \
        -> Tuple[bool, list, list]:
    """
    Measures completion and successfulness of Trust Store update activities by:
    1. checking the status of appliances in the Central Manager inventory
    2. checking all specified appliances for presence of the certificate (actually, the broader cert_config) in the Trust Store
    """
    api_client.authenticate()
    appliances_statuses = api_client.appliances_status()
    status_by_id = {appl['id']: appl for appl in appliances_statuses}
    successes = []
    failures = []
    for appliance_id in appliance_ids:
        status = status_by_id.get(appliance_id)
        if not status:
            raise InvalidApplianceIdError(f'No appliance with id "{appliance_id}" found in Central Management.')
        if not status.get('configurationChannelStatus') == 'up':
            return False, successes, failures
        state = api_client.appliance_status(appliance_id).get('configState')
        match state:
            case 'UP_TO_DATE':
                pass
            case 'APPLY_CONFIG_FAILED':
                failures.append(appliance_id)
            case _:
                return False, successes, failures  # note that these lists are partial but may still be useful
        _, appl_config = api_client.cm_config(appliance_id)
        trusted_certs = appl_config.get('configurableElements', {}).get('trustStore', {}).get('trustedCertificates', [])
        truststore_certs = [cert.get('certificate', {}).get('content') for cert in trusted_certs]
        if not truststore_certs:
            logging.warning(f'Error inspecting the Trust Store for appliance with id {appliance_id}.'
                            f'This is unexpected and may cause inaccurate assessment of Trust Store state.')
        if  presence == (cert in truststore_certs):
            successes.append(appliance_id)
        else:
            failures.append(appliance_id)
    return True, successes, failures


def monitor_completion(api_client: ApiClient, appliance_ids: list[str], cert: str, presence: bool = True,
                       timer: int = 1800, delay: int = 10) -> Tuple[bool, list[str], list[str]]:
    """
    Polls the SNA Manager for completion of Trust Store update activities or until the specified timeout is reached,
    returning a boolean indicating whether the update was successful or not or None if the timeout was reached.

    Note that the timeout isn't a precise "wall-clock" timeout (moreso an approximation) since actions within the
    polling loop aren't necessarily instantaneous and the timeout functions moreso as a loop counter.
    """
    logging.info(f'Monitoring Trust Store state for approximately {timer} seconds...')
    while True:
        complete, successes, failures = check_completion(api_client, appliance_ids, cert, presence)
        if complete:
            return complete, successes, failures
        logging.debug('Appliance updates still in progress...')
        if timer >= 0:
            sleep(delay)
            timer -= delay
        else:
            logging.warning('Time elapsed while monitoring for appliance updates to complete.')
            return complete, successes, failures


def perform_action(manager_address: str, action: str, certfile: str, appliance_fqdns: list[str],
                   verify_false: bool = False, friendly_name: str = '', monitor_timeout: int = 1800):

    def ids_to_fqdns(appl_ids):
        """Convert appliance IDs back to FQDNs using the original mapping."""
        return [appliance_id_fqdn_map.get(appl_id) for appl_id in appl_ids]

    if not Path(certfile).is_file():
        raise ValueError(f'File "{certfile}" does not exist.')

    with open(certfile, 'r') as cert_file:
        cert_content = cert_file.read().rstrip()

    # setup api client
    username, password = _get_credentials()
    client = ApiClient(manager_address, username, password, verify_false)

    client.authenticate()
    appliance_id_fqdn_map = _process_fqdns(client, appliance_fqdns)
    appliance_ids = list(appliance_id_fqdn_map.keys())
    if not appliance_ids:
        logging.error('No matching appliance identified for truststore update/inspection.')
        raise NoMatchingAppliancesError

    match action:
        case 'add':
            if not _is_valid_friendly_name(friendly_name):
                logging.error(f'"{friendly_name}" is not a valid friendly name (can contain only alphanumerics, underscores, hyphens, and periods). Exiting.')
                raise InvalidFriendlyNameError
            logging.info(f'Using "{friendly_name}" as the friendly name for trust store certificates.')

            # one-time establishment of cert config to either send to or verify present on selected appliances
            cert_configs = client.stage_truststore_cert(appliance_ids[0], friendly_name, certfile).json()
            if not cert_configs:
                logging.error('Failed to stage certificate configuration. Exiting.')
                return False
            cert_conf = cert_configs[0]  # seems to only ever have 1; we only intend to support 1 for now anyway
            update_truststores(client, appliance_ids, friendly_name, cert_conf)
            compl, succs, fails = monitor_completion(client, appliance_ids, cert_content, True, monitor_timeout)
            logging.info(f'Trust Store update appears complete.\n'
                         f'Successes: {', '.join(ids_to_fqdns(succs)) or "None"}\n'
                         f'Failures: {', '.join(ids_to_fqdns(fails)) or "None"}')
        case 'del':
            delete_from_truststore(client, appliance_ids, cert_content)
            compl, succs, fails = monitor_completion(client, appliance_ids, cert_content, False, ARGS.monitor_timeout)
            logging.info(f'Trust Store update appears complete.\n'
                         f'Successes: {', '.join(ids_to_fqdns(succs)) or "None"}\n'
                         f'Failures: {', '.join(ids_to_fqdns(fails)) or "None"}')
        case 'check':
            compl, succs, fails = monitor_completion(client, appliance_ids, cert_content, True, ARGS.monitor_timeout)
            logging.info(f'Trust Stores summary:\nCert present on: {', '.join(ids_to_fqdns(succs)) or "None"}\n'
                         f'Cert missing from (or cannot evaluate): {', '.join(ids_to_fqdns(fails)) or "None"}')
        case _:
            logging.error('Unknown action specified. Exiting.')
            raise InvalidActionError
    return compl and not fails


if __name__ == '__main__':
    ARGS = get_command_line_args()
    loglevel = logging.DEBUG if ARGS.debug else logging.INFO
    logging.basicConfig(stream=sys.stdout, level=loglevel,
                        format='%(asctime)s %(levelname)s: %(message)s',  datefmt='%Y-%m-%d %H:%M:%S')
    fqdns = None if ARGS.fqdns == ['all'] else ARGS.fqdns

    try:
        success = perform_action(manager_address=ARGS.manager_address, action=ARGS.action, certfile=ARGS.file,
                       appliance_fqdns=fqdns, verify_false=ARGS.verify_false, friendly_name=ARGS.friendly_name,
                       monitor_timeout=ARGS.monitor_timeout)
        sys.exit(0) if success else sys.exit(1)
    except AuthenticationError:
        logging.error('Failed to authenticate the api client. Exiting.')
        sys.exit(1)
    except FailoverStateException:
        logging.error('The specified Manager is not the primary Manager for this deployment. Exiting.')
        sys.exit(1)
    except requests.exceptions.HTTPError:
        logging.error('An unexpected HTTP status was returned. Exiting.')
        sys.exit(1)
    except (ApplianceStatusError, InvalidApplianceIdError, InvalidApplianceFqdnError, NoMatchingAppliancesError,
            InvalidFriendlyNameError, InvalidActionError) as err:
        logging.error(f'{type(err).__name__}: {err}')
        logging.info('Exiting due to error conditions.')
        sys.exit(1)
